#pragma makedep header

import "wtypes.idl";

cpp_quote("#include <winternl.h>")
cpp_quote("#define SAMR_PROTSEQ {'n','c','a','c','n','_','n','p',0}")
cpp_quote("#define SAMR_ENDPOINT {'\\\\','p','i','p','e','\\\\','s','a','m','r',0}")
cpp_quote("#define SAMR_LOCAL_PROTSEQ {'n','c','a','l','r','p','c',0}")
cpp_quote("#define SAMR_LOCAL_ENDPOINT {'s','a','m','s','s',' ','l','p','c',0}")

[
    uuid(12345778-1234-abcd-ef00-0123456789ac),
    version(1.0),
    pointer_default(unique),
    strict_context_handle
#ifdef SAMR_CLIENT_STUB
    , implicit_handle(handle_t samr_binding)
#endif
]
interface samr
{
    cpp_quote("#if 0")
    typedef LONG NTSTATUS;
    cpp_quote("#endif")

    typedef [context_handle] void *SAMR_HANDLE;

    typedef struct
    {
        USHORT Length;
        USHORT MaximumLength;
        [size_is(MaximumLength / 2), length_is(Length / 2)] WCHAR *Buffer;
    } SAMR_UNICODE_STRING;

    typedef struct
    {
        ULONG RelativeId;
        SAMR_UNICODE_STRING Name;
    } SAMR_RID_ENUMERATION;

    typedef struct
    {
        ULONG EntriesRead;
        [size_is(EntriesRead)] SAMR_RID_ENUMERATION *Buffer;
    } SAMR_ENUMERATION_BUFFER;

    typedef struct
    {
        ULONG Count;
        [size_is(Count)] ULONG *Element;
    } SAMR_ULONG_ARRAY;

    typedef struct
    {
        ULONG Count;
        [size_is(Count)] SAMR_UNICODE_STRING *Element;
    } SAMR_RETURNED_USTRING_ARRAY;

    typedef struct
    {
        ULONG Revision;
        ULONG SupportedFeatures;
    } SAMR_REVISION_INFO_V1;

    typedef [switch_type(ULONG)] union
    {
        [case(1)] SAMR_REVISION_INFO_V1 V1;
    } SAMR_IN_REVISION_INFO;

    typedef [switch_type(ULONG)] union
    {
        [case(1)] SAMR_REVISION_INFO_V1 V1;
    } SAMR_OUT_REVISION_INFO;

    typedef struct
    {
        ULONG LowPart;
        LONG HighPart;
    } SAMR_OLD_LARGE_INTEGER;

    typedef struct
    {
        USHORT Length;
        USHORT MaximumLength;
        [size_is(MaximumLength / 2), length_is(Length / 2)] USHORT *Buffer;
    } SAMR_SHORT_BLOB;

    typedef struct
    {
        [range(0, 256 * 1024)] ULONG Length;
        [size_is(Length)] BYTE *SecurityDescriptor;
    } SAMR_SECURITY_DESCRIPTOR;

    typedef struct
    {
        USHORT UnitsPerWeek;
        [size_is(1260), length_is((UnitsPerWeek + 7) / 8)] BYTE *LogonHours;
    } SAMR_LOGON_HOURS;

#pragma pack(push, 4)
    typedef struct
    {
        SAMR_OLD_LARGE_INTEGER LastLogon;
        SAMR_OLD_LARGE_INTEGER LastLogoff;
        SAMR_OLD_LARGE_INTEGER PasswordLastSet;
        SAMR_OLD_LARGE_INTEGER AccountExpires;
        SAMR_OLD_LARGE_INTEGER PasswordCanChange;
        SAMR_OLD_LARGE_INTEGER PasswordMustChange;
        SAMR_UNICODE_STRING UserName;
        SAMR_UNICODE_STRING FullName;
        SAMR_UNICODE_STRING HomeDirectory;
        SAMR_UNICODE_STRING HomeDirectoryDrive;
        SAMR_UNICODE_STRING ScriptPath;
        SAMR_UNICODE_STRING ProfilePath;
        SAMR_UNICODE_STRING AdminComment;
        SAMR_UNICODE_STRING WorkStations;
        SAMR_UNICODE_STRING UserComment;
        SAMR_UNICODE_STRING Parameters;
        SAMR_SHORT_BLOB LmOwfPassword;
        SAMR_SHORT_BLOB NtOwfPassword;
        SAMR_UNICODE_STRING PrivateData;
        SAMR_SECURITY_DESCRIPTOR SecurityDescriptor;
        ULONG UserId;
        ULONG PrimaryGroupId;
        ULONG UserAccountControl;
        ULONG WhichFields;
        SAMR_LOGON_HOURS LogonHours;
        USHORT BadPasswordCount;
        USHORT LogonCount;
        USHORT CountryCode;
        USHORT CodePage;
        BYTE LmPasswordPresent;
        BYTE NtPasswordPresent;
        BYTE PasswordExpired;
        BYTE PrivateDataSensitive;
    } SAMR_USER_ALL_INFORMATION;
#pragma pack(pop)

    typedef struct
    {
        ULONG Size;
        [size_is(Size)] BYTE *Data;
    } SAMR_BYTE_ARRAY;

    typedef struct
    {
        ULONG Value;
        USHORT Field1;
        USHORT Field2;
        BYTE Data[8];
    } SAMR_EXTENDED_INLINE;

    typedef struct
    {
        ULONG ExtendedWhichFields;
        SAMR_BYTE_ARRAY UserTile;
        SAMR_UNICODE_STRING PasswordHint;
        BYTE DontShowInLogonUI;
        SAMR_BYTE_ARRAY ShellAdminObjectProperties;
        SAMR_UNICODE_STRING ReservedString1;
        SAMR_UNICODE_STRING ReservedString2;
        SAMR_EXTENDED_INLINE ReservedInline;
        SAMR_UNICODE_STRING ReservedString3;
        SAMR_BYTE_ARRAY ReservedBlob1;
        SAMR_BYTE_ARRAY ReservedBlob2;
        ULONG ReservedFlags;
    } SAMR_USER_EXTENDED_INFORMATION;

    typedef struct
    {
        BYTE PasswordIsBlank;
        BYTE AccountIsDisabled;
    } SAMR_USER_LOGON_UI_INFORMATION;

    typedef struct
    {
        ULONG WhichFields;
        SAMR_UNICODE_STRING ResetData;
    } SAMR_USER_AUTH_INFORMATION;

    typedef enum
    {
        SamrUserAllInformation = 21,
        SamrUserExtendedInformation = 28,
        SamrUserLogonUIInformation = 29,
        SamrUserAuthInformation = 30
    } SAMR_USER_INFORMATION_CLASS;

    typedef [switch_type(SAMR_USER_INFORMATION_CLASS)] union
    {
        [case(SamrUserAllInformation)] SAMR_USER_ALL_INFORMATION All;
        [case(SamrUserExtendedInformation)] SAMR_USER_EXTENDED_INFORMATION Extended;
        [case(SamrUserLogonUIInformation)] SAMR_USER_LOGON_UI_INFORMATION LogonUI;
        [case(SamrUserAuthInformation)] SAMR_USER_AUTH_INFORMATION Auth;
    } SAMR_USER_INFO_BUFFER;

    NTSTATUS samr_unused_0(void);
    NTSTATUS samr_close_handle([in, out] SAMR_HANDLE *handle);
    NTSTATUS samr_unused_2(void);
    NTSTATUS samr_unused_3(void);
    NTSTATUS samr_unused_4(void);
    NTSTATUS samr_lookup_domain_in_server(
        [in] SAMR_HANDLE server_handle,
        [in] SAMR_UNICODE_STRING *name,
        [out] SID **domain_sid);
    NTSTATUS samr_enumerate_domains_in_server(
        [in] SAMR_HANDLE server_handle,
        [in, out] ULONG *enumeration_context,
        [out] SAMR_ENUMERATION_BUFFER **buffer,
        [in] ULONG preferred_maximum_length,
        [out] ULONG *count_returned);
    NTSTATUS samr_open_domain(
        [in] SAMR_HANDLE server_handle,
        [in] ULONG desired_access,
        [in] SID *domain_sid,
        [out] SAMR_HANDLE *domain_handle);
    NTSTATUS samr_unused_8(void);
    NTSTATUS samr_unused_9(void);
    NTSTATUS samr_unused_10(void);
    NTSTATUS samr_unused_11(void);
    NTSTATUS samr_unused_12(void);
    NTSTATUS samr_enumerate_users_in_domain(
        [in] SAMR_HANDLE domain_handle,
        [in, out] ULONG *enumeration_context,
        [in] ULONG user_account_control,
        [out] SAMR_ENUMERATION_BUFFER **buffer,
        [in] ULONG preferred_maximum_length,
        [out] ULONG *count_returned);
    NTSTATUS samr_unused_14(void);
    NTSTATUS samr_unused_15(void);
    NTSTATUS samr_unused_16(void);
    NTSTATUS samr_lookup_names_in_domain(
        [in] SAMR_HANDLE domain_handle,
        [in, range(0, 1000)] ULONG count,
        [in, size_is(1000), length_is(count)] SAMR_UNICODE_STRING names[*],
        [out] SAMR_ULONG_ARRAY *relative_ids,
        [out] SAMR_ULONG_ARRAY *use);
    NTSTATUS samr_lookup_ids_in_domain(
        [in] SAMR_HANDLE domain_handle,
        [in, range(0, 1000)] ULONG count,
        [in, size_is(1000), length_is(count)] ULONG relative_ids[*],
        [out] SAMR_RETURNED_USTRING_ARRAY *names,
        [out] SAMR_ULONG_ARRAY *use);
    NTSTATUS samr_unused_19(void);
    NTSTATUS samr_unused_20(void);
    NTSTATUS samr_unused_21(void);
    NTSTATUS samr_unused_22(void);
    NTSTATUS samr_unused_23(void);
    NTSTATUS samr_unused_24(void);
    NTSTATUS samr_unused_25(void);
    NTSTATUS samr_unused_26(void);
    NTSTATUS samr_unused_27(void);
    NTSTATUS samr_unused_28(void);
    NTSTATUS samr_unused_29(void);
    NTSTATUS samr_unused_30(void);
    NTSTATUS samr_unused_31(void);
    NTSTATUS samr_unused_32(void);
    NTSTATUS samr_unused_33(void);
    NTSTATUS samr_open_user(
        [in] SAMR_HANDLE domain_handle,
        [in] ULONG desired_access,
        [in] ULONG user_id,
        [out] SAMR_HANDLE *user_handle);
    NTSTATUS samr_unused_35(void);
    NTSTATUS samr_query_information_user(
        [in] SAMR_HANDLE user_handle,
        [in] SAMR_USER_INFORMATION_CLASS user_information_class,
        [out, switch_is(user_information_class)] SAMR_USER_INFO_BUFFER **buffer);
    NTSTATUS samr_unused_37(void);
    NTSTATUS samr_unused_38(void);
    NTSTATUS samr_unused_39(void);
    NTSTATUS samr_unused_40(void);
    NTSTATUS samr_unused_41(void);
    NTSTATUS samr_unused_42(void);
    NTSTATUS samr_unused_43(void);
    NTSTATUS samr_unused_44(void);
    NTSTATUS samr_unused_45(void);
    NTSTATUS samr_unused_46(void);
    NTSTATUS samr_unused_47(void);
    NTSTATUS samr_unused_48(void);
    NTSTATUS samr_unused_49(void);
    NTSTATUS samr_unused_50(void);
    NTSTATUS samr_unused_51(void);
    NTSTATUS samr_unused_52(void);
    NTSTATUS samr_unused_53(void);
    NTSTATUS samr_unused_54(void);
    NTSTATUS samr_unused_55(void);
    NTSTATUS samr_unused_56(void);
    NTSTATUS samr_unused_57(void);
    NTSTATUS samr_unused_58(void);
    NTSTATUS samr_unused_59(void);
    NTSTATUS samr_unused_60(void);
    NTSTATUS samr_unused_61(void);
    NTSTATUS samr_connect4(
        [in, unique, string] WCHAR *server_name,
        [out] SAMR_HANDLE *server_handle,
        [in] ULONG client_revision,
        [in] ULONG desired_access);
    NTSTATUS samr_unused_63(void);
    NTSTATUS samr_connect5(
        [in, unique, string] WCHAR *server_name,
        [in] ULONG desired_access,
        [in] ULONG in_version,
        [in, switch_is(in_version)] SAMR_IN_REVISION_INFO *in_revision_info,
        [out] ULONG *out_version,
        [out, switch_is(*out_version)] SAMR_OUT_REVISION_INFO *out_revision_info,
        [out] SAMR_HANDLE *server_handle);
    NTSTATUS samr_rid_to_sid(
        [in] SAMR_HANDLE object_handle,
        [in] ULONG relative_id,
        [out] SID **sid);
    NTSTATUS samr_unused_66(void);
    NTSTATUS samr_unused_67(void);
    NTSTATUS samr_unused_68(void);
    NTSTATUS samr_unused_69(void);
    NTSTATUS samr_unused_70(void);
    NTSTATUS samr_lookup_names_in_domain2(
        [in] SAMR_HANDLE domain_handle,
        [in, range(0, 1000)] ULONG count,
        [in, size_is(1000), length_is(count)] SAMR_UNICODE_STRING names[*],
        [out] SAMR_ULONG_ARRAY *relative_ids,
        [out] SAMR_ULONG_ARRAY *use);
    NTSTATUS samr_enumerate_users_in_domain2(
        [in] SAMR_HANDLE domain_handle,
        [in, out] ULONG *enumeration_context,
        [in] ULONG user_account_control,
        [in] ULONG account_kind_filter,
        [out] SAMR_ENUMERATION_BUFFER **buffer,
        [in] ULONG preferred_maximum_length,
        [out] ULONG *count_returned);
}
