/*
 * Copyright 2019 Louis Lenders
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

import "oaidl.idl";

[
    object,
    uuid(82ba7092-4c88-427d-a7bc-16dd93feb67e),
    pointer_default(unique)
]
interface IRestrictedErrorInfo : IUnknown
{
    HRESULT GetErrorDetails (
        [out] BSTR *desc,
        [out] HRESULT *error,
        [out] BSTR *restricted_desc,
        [out] BSTR *sid);

    HRESULT GetReference ([out] BSTR *reference);
}

[
    object,
    uuid(04a2dbf3-df83-116c-0946-0812abf6e07d),
    pointer_default(unique)
]
interface ILanguageExceptionErrorInfo : IUnknown
{
    HRESULT GetLanguageException ([out] IUnknown **language_exception);
}

[
    object,
    uuid(5746e5c4-5b97-424c-b620-2822915734dd),
    pointer_default(unique)
]
interface ILanguageExceptionErrorInfo2 : ILanguageExceptionErrorInfo
{
    HRESULT GetPreviousLanguageExceptionErrorInfo (
        [out] ILanguageExceptionErrorInfo2 **previous);

    HRESULT CapturePropagationContext ([in] IUnknown *language_exception);

    HRESULT GetPropagationContextHead (
        [out] ILanguageExceptionErrorInfo2 **head);
}
