@ stdcall PdcAcquireRwLockExclusive(ptr)
@ stdcall PdcActivationClientActivityRequest(ptr long long int64)
@ stdcall PdcActivationClientRegister(long ptr)
@ stdcall PdcActivationClientUnregister(ptr)
@ stdcall PdcAllocate(ptr int64)
@ stdcall PdcFree(ptr)
@ stdcall PdcNotificationClientAcknowledge(ptr long)
@ stdcall PdcNotificationClientRegister(ptr ptr ptr ptr)
@ stdcall PdcNotificationClientUnregister(ptr)
@ stdcall PdcPortClose(ptr)
@ stdcall PdcPortOpen(long long ptr ptr ptr long ptr ptr)
@ stdcall PdcPortSendMessage(ptr ptr long)
@ stdcall PdcPortSendMessageSynchronously(ptr ptr long)
@ stdcall PdcPpmProfileClientRegister(ptr ptr)
@ stdcall PdcPpmProfileClientUnregister(ptr)
@ stdcall PdcPpmProfileDisable(ptr)
@ stdcall PdcPpmProfileEnable(ptr long)
@ stdcall PdcReleaseRwLockExclusive(ptr)
@ stdcall PdcResiliencyClientAcknowledge()
@ stdcall PdcResiliencyClientRegister(long ptr ptr ptr)
@ stdcall PdcResiliencyClientUnregister(ptr)
@ stdcall PdcRwLockInitialize(ptr)
@ stdcall PdcSignalClientPulse(ptr ptr)
@ stdcall PdcSignalClientRegister(ptr ptr)
@ stdcall PdcSignalClientSetActive(ptr long ptr)
@ stdcall PdcSignalClientUnregister(ptr)
@ stdcall PdcSleep(long)
@ stdcall PdcTaskClientRegister(long ptr)
@ stdcall PdcTaskClientRequest(ptr long)
@ stdcall PdcTaskClientUnregister(ptr)
@ stdcall Pdcv2ActivationClientActivate(ptr ptr ptr long ptr long ptr ptr)
@ stdcall Pdcv2ActivationClientDeactivate(ptr)
@ stdcall Pdcv2ActivationClientRegister(long ptr ptr)
@ stdcall Pdcv2ActivationClientRenewActivation(ptr ptr ptr)
@ stdcall Pdcv2ActivationClientSetBrokeredProcessId(ptr long)
@ stdcall Pdcv2ActivationClientUnregister(ptr ptr)
@ stdcall SleepstudyHelperBlockerActiveDereference(ptr)
@ stdcall SleepstudyHelperBlockerActiveReference(ptr)
@ stdcall SleepstudyHelperBuildBlocker(ptr ptr)
@ stdcall SleepstudyHelperCreateBlockerFromGuid(ptr ptr ptr ptr long ptr)
@ stdcall SleepstudyHelperCreateLibrary(long ptr)
@ stdcall SleepstudyHelperCreateLibraryEx(ptr ptr)
@ stdcall SleepstudyHelperDestroyBlocker(ptr)
@ stdcall SleepstudyHelperDestroyBlockerBuilder(ptr)
@ stdcall SleepstudyHelperDestroyLibrary(ptr)
@ stdcall SleepstudyHelperGetBlockerGuid(ptr ptr)
@ stdcall SleepstudyHelperSetBlockerFriendlyName(ptr ptr)
@ stdcall SleepstudyHelperSetBlockerParentHandle(ptr ptr)
@ stdcall SleepstudyHelperSetBlockerVisible(ptr long)
